security:
    encoders:
        App\Entity\Particulier:
            algorithm: auto
        App\Entity\Professionnel:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        particulier_provider:
            entity:
                class: App\Entity\Particulier
                property: email
        professionnel_provider:
            entity:
                class: App\Entity\Professionnel
                property: siret
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        particulier_security:
            pattern: ^/particulier
            anonymous: true
            provider: particulier_provider
            guard:
                authenticators:
                    - App\Security\ParticulierAuthenticator
            logout:
                path: deco_part
                # where to redirect after logout
                target: /
        professionnel_security:
            pattern: ^/professionnel
            anonymous: true
            provider: professionnel_provider
            guard:
                authenticators:
                    - App\Security\ProfessionnelAuthenticator
            logout:
                path: deco_pro
                # where to redirect after logout
                target: /
        # main:
        #     anonymous: true
        #     guard:
        #         authenticators:
        #             - App\Security\LoginFormAuthenticator
        #     logout:
        #         path: deconnexion
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
